services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo17-web
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - novago-web-data:/var/lib/odoo
      - ./NOVAGO:/mnt/extra-addons
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    restart: always

  db:
    image: postgres:15
    container_name: odoo17-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - novago-db-data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    container_name: odoo17-adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: always

volumes:
  novago-web-data:
  novago-db-data: