git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_certification.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_commission.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_consent_form.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_document_base.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_documents_preview.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_aesthetic.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_all.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_ambulance.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_barcode.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_base.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_blood_bank.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_body_chart.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_certification.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_commission.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_consent_form.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_dashboard.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_dental.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_dental_chart.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_documents_preview.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_emergency.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_geriatrics.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_gynec.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_hospitalization.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_icd10.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_insurance.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_insurance_hospitalization.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_insurance_laboratory.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_insurance_radiology.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_insurance_surgery.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_invoice_summary.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_laboratory.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_laboratory_hospitalization.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_medical_representative.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_next_patient_screen.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_nursing.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_online_appointment.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_operation_theater.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_ophthalmology.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_paediatric.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_pharmacy.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_pharmacy_pos.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_physiotherapy.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_portal.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_pro.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_radiology.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_radiology_hospitalization.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_rating.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_recurring_procedure.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_sms.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_spreadsheet_dashboard.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_subscription.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_subscription_physiotherapy.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_surgery.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_survey.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_vaccination.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_video_call.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_vital_examination.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_webcam.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_whatsapp.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/igs_hms_custom.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/invoice_barcode.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/invoice_with_stock_move.git
git clone	https://git.veone.net/veone/odoo/addons/ee/hms/web_timer_widget.git
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_invoice_split.git
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_invoice_summary.git    
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_jitsi_meet.git    
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_laboratory.git
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_laboratory_website_booking.git
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_laboratory_whatsapp.git 
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_pharmacy.git    
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_pharmacy_whatsapp.git    
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_portal_user_image.git
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_product_barcode_generator.git    
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_radiology.git 
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_radiology_whatsapp.git    
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_sms.git 
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_subscription.git    
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_video_call.git
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_webcam.git    
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_website_booking.git    
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_whatsapp.git
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_whatsapp_meta.git    
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/facility_management.git
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/igs_hms_custom.git 
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_insurance_custom.git
git clone   https://git.veone.net/veone/odoo/addons/ee/hms/acs_hms_insurance_computation.git